### ISSUE TITLE
EIF bit-by-bit reproducibility vs Nitro Util

### ISSUE THREAD

**Issue by roshanr95** [monzo/aws-nitro-util#19]
The README says "no, EIFs are timestamped" against nitro-cli for reproducability which might be worth clarifying. The nitro-cli tool itself produces reproducible builds given the same docker image (on the same system for sure, probably over different systems as well). It's the Docker images themselves that are usually timestamped.

**Comment by Cottand** [comment]
Hi @roshanr95 !

Docker images definitely tend to be timestamped and a source of indeterminism, but I do believe the Nitro CLI sets another timestamp outside of the image's.

My understanding of where the timestamp comes from is from reading the `encalve_build` folder in the Nitro CLI source. Specifically, I see a timestamp included in the `EifBuildInfo` struct. I believe that is constructed [here](https://github.com/aws/aws-nitro-enclaves-cli/blob/main/src/lib.rs#L121):

```rust
let build_info = generate_build_info!(&format!("{}.config", kernel_path)).map_err(|e| {

```

And then that function uses a new timestamp each time it is called, as seen in [enclave-format](https://github.com/aws/aws-nitro-enclaves-image-format/blob/5a69099b6c40505369eca8e27e26ec0b3a168f0b/src/utils/identity.rs#L37C9-L37C38), inside `generate_build_info()`:
```rust
let now = Utc::now();

Ok(EifBuildInfo {
    build_time: now.to_rfc3339(),
})
```

More empirically, when we developed this repo, we had to set the timestamp manually [here](https://github.com/monzo/aws-nitro-util/blob/master/eif-cli/src/main.rs#L194) in order to override what `generate_build_info()` produced. Additionally, when we did use the Nitro CLI, if I remember correctly we got EIFs with different hashes even when using the exact same Docker image twice.


I am by no means a Rust developer, so I could have misread and the timestamps in EIFs could come from elsewhere. Do correct if this is the case! I would hate for the README to be inaccurate.

**Comment by roshanr95** [comment]
hmm, when I do `nitro-cli build-enclave --docker-uri <tag> --output-file <eif>`, I always get the same PCRs on repeated attempts, is that not the same for you? I'm now wondering why that is the case when the code seems to clearly be using timestamps in the metadata :sweat_smile:

**Comment by Cottand** [comment]
Ah, that's because the PCRs do not include metadata (which is where the timestamp is). See [this article](https://blog.trailofbits.com/2024/02/16/a-few-notes-on-aws-nitro-enclaves-images-and-attestation/) for a good explanation. If you build the same EIF twice, you get the same PCRs, but not the same SHA256 of the file itself.

Image from that article further below. See how `EifSectionMetadata` is not part of any PCR.

This repo, on the other hand, will actually produce EIF fils with the same SHA256 every time (assuming you always use the same input for the `copyToRoot` part)

![image](https://github.com/monzo/aws-nitro-util/assets/45274424/5d769b08-0a5a-4f92-a3f5-9913252cbcf4)

**Comment by Cottand** [comment]
This is why in the README we say "**Bit-by-bit** reproducible EIFs". Do let me know if you think some different working might make that clearer

**Comment by roshanr95** [comment]
Ah got it, I misunderstood.
